### ISSUE TITLE
Provide versioned binary releases 

### ISSUE THREAD

**Issue by drubin** [yannh/terraform-provider-statuspage#15] opened 2020-01-19 15:52 UTC
Currently the only releleases are from the master branch on gitlab's ci jobs. 

It would be nice to provide versioned binaries for multiple platforms. Submitted as release artifacts.

I have a WIP branch adding this using goreleser would this be something you would accept?

**Comment by yannh** [comment] 2020-01-19 16:02
Hi! I admit I'm not too familiar with automatically creating Github releases / goreleaser. Providing binaries for multiple platforms definitely sounds like something that wouldn't be interesting - as for the releases, do you think it could be done while keeping the CI with gitlab-ci?

**Comment by drubin** [comment] 2020-01-19 16:15
> ...multiple platforms definitely sounds like something that wouldn't be interesting...

Or would? :)

> do you think it could be done while keeping the CI with gitlab-ci?

We can do either or I guess the issue is more about where you want to publish the released binaries. AFAIK gitlab doesn't support attaching binaries to tags/releases yet so I think it would be better to publish them to github(it's also where the other providers push theirs). it seems github is your primary git repo and the gitlab is just a mirror?

The biggest thing with keeping gitlab is you will manually need to configure a gitlab secret with the github token to do the uploading but this is trivial to add. 

If this is something you would be willing to accept I can clean up my branch and send an PR. 

Currently my branch is using github actions as I think the token access is automatic then but it won't be hard to make it use gitlab if that is what you would prefer?

**Comment by yannh** [comment] 2020-01-19 16:18
Ahah yes, would be interesting to support more platforms sorry :man_facepalming:  Github is the primary repo, Gitlab is used for the CI. Happy to publish binaries on Github. I'll review what kind of tokens I can issue and if I can restrict what it can do to this project :)

**Comment by drubin** [comment] 2020-02-18 22:23
I forgot to revisit this. I have been using my own fork with manually uploaded binaries.  I will try get to this again.

**Comment by htonkovac** [comment] 2020-04-22 10:31
@yannh @drubin
Have you considered implementing this?
It would be of great benefit to have versioned releases (version 1.0, version 1.1, etc.)

**Comment by drubin** [comment] 2020-04-22 10:35
@htonkovac I love Gitlab and use it regularly but I have no real interest in building gitlab-ci for a project hosted primarily on Github it complicates things... 

If @yannh was willing to support Github actions I would gladly throw together a PR supporting automatic releases (its trivial and I believe the integration is seamless) 

https://github.com/goreleaser/goreleaser-action 

@yannh Would you be willing to accept a PR that adds GitHub actions?

**Comment by yannh** [comment] 2020-04-22 10:55
Yes, Github actions are fine! Thanks a lot!

**Comment by yannh** [comment] 2020-06-21 10:35
Alright I've migrated the CI from Gitlab-CI to github actions... @drubin the work is heavily inspired from your PR, but a bit different - I am not comfortable with the scope of Github Tokens (can not scope the token to a single project), and accidentally exposing it would be.. bad, therefore I'll be triggering the releases locally.  Thanks a lot!

**Comment by htonkovac** [comment] 2020-06-21 10:37
Awesome work @yannh 😎

**Comment by drubin** [comment] 2020-06-21 10:38
@yannh what scoping? They are only by default and only avaliable on your repo not on forks.

**Comment by drubin** [comment] 2020-06-21 10:40
The reason for doing it from github actions is so the audit trail is public aand open. This way there is a verified releases.

If these are manually built and uploaded you loose all that.

**Comment by yannh** [comment] 2020-06-21 10:56
I get that, and I get that Github in theory protects the secrets from being accessed by external PRs - but the token enables access to a wide range of internal repos I have access to, and I don't want to risk accidental exposure. I would need the Github token to be limited to this repository - or Github actions to enable releases for a repo from the CI from the same repo without auth.

I'm not sure about the audit trail here - I could very well delete the release created by goreleaser and create another one manually, it wouldn't be obvious that the release is not created from CI. I wouldn't suggest to trust this.

However - dependencies are vendored, and we build within docker. If I pinned the docker image to a hash, we should be able to get reproducible builds. This way anyone should be able to verify the checksums of the distributed binaries. Ultimately that's probably the only way to guarantee the binaries are indeed built from the distributed sources. WDYT?

**Comment by yannh** [comment] 2020-06-21 11:40
Alright I updated the configuration of goreleaser to try to generate reproducible builds. While I pinned the version of the goreleaser image, I ultimately don't have control over the toolchain.. so I guess re-running goreleaser would be the way to verify the checksums :thinking: 
I'll close this ticket since there are binary releases now - I'd be happy to work more on the reproducibility / binary verification aspect, so feel free to open another ticket along those lines :) Thanks a lot for your help with goreleaser! :+1:

**Comment by drubin** [comment] 2020-06-21 15:19
> I get that, and I get that Github in theory protects the secrets from being accessed by external PRs - but the token enables access to a wide range of internal repos I have access to, and I don't want to risk accidental exposure. I would need the Github token to be limited to this repository - or Github actions to enable releases for a repo from the CI from the same repo without auth.

@yannh Thanks for merging this and for providing binary releases. There are however a  few points I would like to address. 

 ### Concerns about security.

You aren't the first and only person in this situation every single other developer on GitHub has the same issues and luckily they have taken this into account when designing actions.

The auth token that I mentioned is automatically injected by Github on every action regardless of how you configure it. This is not something you manually generate and then add to Github. So the access is there whether you use it or not.

**The security model is what code exists in your repo. Which you control.**

https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret

> When you enable GitHub Actions, GitHub installs a GitHub App on your repository. The GITHUB_TOKEN secret is a GitHub App installation access token. You can use the installation access token to authenticate on behalf of the GitHub App installed on your repository. The token's permissions are limited to the repository that contains your workflow. 

> so I guess re-running goreleaser would be the way to verify the checksums 🤔

This is very unlikely as binaries have versions/commits and other information built into them.  Unless you are actively building for reproducible builds I doubt this will happen or is needed. 

The chain of trust should be roughly 

1. Source code 
2. Builds 
3. Binaries 

The greatest win we get with opensource is not only being able to verify the source code but also the build history/trust chain. You loose this when the releases come from an unknown process. Sometimes that unavoidable but in this case, it's an easy fix.

I would really like to ask you to re-consider having Github actions publish the binaries on your behalf.

**Comment by yannh** [comment] 2020-06-21 15:47
Ok @drubin I missed an important part here - I did not know realize Actions auto-generated a GITHUB_TOKEN as part of the workflow, and thought I had to use a "regular" github token that would not be restricted to the current repository as a secret - and would likely give access to all private repos I have access to.
Indeed this is very fixable then :+1: 

I would like to stress however - there is no chain of trust here. This does not guarantee the binaries are generated from the sources in this repo. It is possible for any repo owner to edit/ change the releases and replace downloadable assets with whatever they see fit. If you need full trust - re-build!

There are a few things we could do however:
 * Sign the checksums file. That would guarantee that *I* generated the binaries. This would mean you trust me to generate appropriate binaries. As part of the CI I guess it loses a bit of value since I'd have to give Github ACtions permission to sign on my behalf.
 * Reproducible builds: If you need validation that the binary indeed comes from the source code within this repository. Some literature available here > https://reproducible-builds.org/ . 

However:
 * You need to automate the verification of the signature, and the checksums of the files (this is usually done behind the scene by your favourite package manager, but we lose this here). 
 * Reproducible builds - is a lot more tricky. Essentially, you would need to rebuild to validate that you are getting the same files.

We should probably do both. But it is only secure if the claims are easily verifiable.

**Comment by yannh** [comment] 2020-06-21 17:44
Alright : 
![image](https://user-images.githubusercontent.com/210669/85231457-5efaa500-b3f7-11ea-92ec-43fd372503f8.png)

Thanks again! :+1:

**Closed by yannh** 2020-06-21 17:44 UTC

**Comment by drubin** [comment] 2020-06-21 18:30
No thank you @yannh :) hope you have a great evening. We will give it a spin and give more feedback. 

It would be great to ditch our internal fork :)
